// Generated from site-checklist.md — do not edit by hand; edit the checklist and
// regenerate (kept sites only). Opencli itself is untouched; this prunes what the
// agent can see and call. qwen domain: https://chat.qwen.ai/

const KEPT: string[] = ["12306","1688","51job","aibase","amazon","antigravity","apple-podcasts","archive","arxiv","autohome","band","barchart","bbc","binance","bloomberg","bluesky","booking","brave","chatgpt","chatgpt-app","chatwise","chess","claude","codex","coingecko","confluence","crates","cursor","deepseek","defillama","devto","dictionary","discord-app","dockerhub","duckduckgo","eastmoney","endoflife","facebook","flathub","gemini","geogebra","gitee","github","github-trending","google","google-scholar","goproxy","grok","hackernews","hf","hltv","homebrew","imdb","indeed","instagram","jira","kimi","lichess","linkedin","linkedin-learning","linux-do","lobsters","manus","maven","mdn","medium","mercury","midjourney","notebooklm","npm","nuget","nvd","oeis","ones","openalex","openfda","openreview","osv","packagist","paperreview","pinterest","pixiv","producthunt","pubmed","pypi","qoder","qwen","reddit","rednote","rest-countries","rfc","rubygems","semanticscholar","spotify","stackoverflow","steam","substack","tiktok","tvmaze","twitter","uisdc","uiverse","upwork","web","weread","weread-official","wikidata","wikipedia","youtube","zlibrary"];
const REMOVED: string[] = ["1point3acres","36kr","baidu-scholar","bilibili","boss","chaoxing","cnki","coupang","ctrip","dblp","dianping","dongchedi","douban","doubao","doubao-app","douyin","flomo","gov-law","gov-policy","guazi","huodongxing","hupu","jd","jianyu","jike","jimeng","juejin","ke","lesswrong","maimai","mubu","nowcoder","powerchina","quark","reuters","sinablog","sinafinance","slock","smzdm","suno","taobao","tdx","ths","tieba","toutiao","trae-cn","trae-solo","trip","v2ex","wanfang","wechat-channels","weibo","weixin","wttr","xianyu","xiaoe","xiaohongshu","xiaoyuzhou","xueqiu","yahoo","yahoo-finance","yollomi","youdao","yuanbao","zhihu","zsxq"];

export const ALLOWED_SITES: ReadonlySet<string> = new Set(KEPT);
export const REMOVED_SITES: ReadonlySet<string> = new Set(REMOVED);
